name: Mirroring

on: [push, delete]

jobs:
  to_codeberg:
    runs-on: ubuntu-latest
    steps:                  
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@674e65a7d483ca28dafaacba0d07351bdcc8bd75 # v1
        with:
          target_repo_url:
            git@codeberg.org:EchoNine/Kite.git
          ssh_private_key:                             
            ${{ secrets.CODEBERG_MIRROR_PRIVATE_KEY }}
